"""Normative enumerations from the specification set.

Values are SCREAMING_SNAKE_CASE per 02_LISTING_DATA_SCHEMA.md §5.2. These enums are
shared by the Pydantic contracts and the SQLAlchemy models (stored as constrained
text, never native PostgreSQL enums, so values can evolve by migration).

UNKNOWN / NOT_STATED / NOT_APPLICABLE / CONFLICTING / NEGATIVE / UNAVAILABLE are
distinct semantic states (02 §3.4) and must never be collapsed into NULL.
"""

from enum import StrEnum


class SourceType(StrEnum):
    LISTING = "LISTING"
    GEOCODER = "GEOCODER"
    ROUTING = "ROUTING"
    TRANSIT_DATA = "TRANSIT_DATA"
    MEDIA = "MEDIA"
    SEARCH_INDEX = "SEARCH_INDEX"
    OTHER = "OTHER"


class AccessMethod(StrEnum):
    API = "API"
    FEED = "FEED"
    BROWSER = "BROWSER"
    MANUAL_IMPORT = "MANUAL_IMPORT"
    OTHER_APPROVED = "OTHER_APPROVED"


class SourceApprovalStatus(StrEnum):
    PROPOSED = "PROPOSED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    SUSPENDED = "SUSPENDED"
    REJECTED = "REJECTED"


class RefreshTriggerType(StrEnum):
    SCHEDULED = "SCHEDULED"
    MANUAL = "MANUAL"
    REPLAY = "REPLAY"
    RETRY = "RETRY"


class RefreshRunStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class SourceRunStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    CANCELLED = "CANCELLED"


class ParseStatus(StrEnum):
    VALID = "VALID"
    PARTIAL = "PARTIAL"
    INVALID = "INVALID"
    BLOCKED = "BLOCKED"


class ContactRedactionStatus(StrEnum):
    NOT_PRESENT = "NOT_PRESENT"
    IGNORED = "IGNORED"
    REDACTED = "REDACTED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class LocationPrecision(StrEnum):
    ROOFTOP_OR_ENTRANCE = "ROOFTOP_OR_ENTRANCE"
    BUILDING = "BUILDING"
    PARCEL = "PARCEL"
    INTERPOLATED_ADDRESS = "INTERPOLATED_ADDRESS"
    STREET = "STREET"
    POSTAL_CODE = "POSTAL_CODE"
    NEIGHBORHOOD = "NEIGHBORHOOD"
    CITY = "CITY"
    UNKNOWN = "UNKNOWN"


class GeocodeStatus(StrEnum):
    PENDING = "PENDING"
    VALID = "VALID"
    WARNING = "WARNING"
    FAILED = "FAILED"
    MANUAL = "MANUAL"


class BoundaryStatus(StrEnum):
    IN_SCOPE = "IN_SCOPE"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"
    UNRESOLVED = "UNRESOLVED"


class AddressAssertionStatus(StrEnum):
    SUPPORTED = "SUPPORTED"
    APPROXIMATE = "APPROXIMATE"
    CONFLICTING = "CONFLICTING"
    REJECTED = "REJECTED"


class AddressMatchMethod(StrEnum):
    EXACT_NORMALIZED = "EXACT_NORMALIZED"
    GEOCODER = "GEOCODER"
    FUZZY = "FUZZY"
    MANUAL = "MANUAL"


class Confidence(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNKNOWN = "UNKNOWN"


class PropertyType(StrEnum):
    APARTMENT_BUILDING = "APARTMENT_BUILDING"
    CONDO = "CONDO"
    COOP = "COOP"
    TOWNHOUSE = "TOWNHOUSE"
    MULTIFAMILY = "MULTIFAMILY"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class BuildingIdentityStatus(StrEnum):
    CONFIRMED = "CONFIRMED"
    PROVISIONAL = "PROVISIONAL"
    CONFLICTING = "CONFLICTING"
    MANUALLY_RESOLVED = "MANUALLY_RESOLVED"


class UnitIdentityStatus(StrEnum):
    CONFIRMED = "CONFIRMED"
    PROVISIONAL = "PROVISIONAL"
    WITHHELD_LABEL = "WITHHELD_LABEL"
    CONFLICTING = "CONFLICTING"
    MANUALLY_RESOLVED = "MANUALLY_RESOLVED"


class LayoutClass(StrEnum):
    STUDIO = "STUDIO"
    ONE_BEDROOM = "ONE_BEDROOM"
    TWO_BEDROOM = "TWO_BEDROOM"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"
    UNKNOWN = "UNKNOWN"
    CONFLICTING = "CONFLICTING"


class AvailabilityStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    AVAILABLE_FUTURE = "AVAILABLE_FUTURE"
    APPLICATION_PENDING = "APPLICATION_PENDING"
    NO_LONGER_AVAILABLE = "NO_LONGER_AVAILABLE"
    SOURCE_REMOVED = "SOURCE_REMOVED"
    UNKNOWN = "UNKNOWN"
    CONFLICTING = "CONFLICTING"


class LifecycleStatus(StrEnum):
    CANDIDATE = "CANDIDATE"
    ACTIVE = "ACTIVE"
    MISSING = "MISSING"
    INACTIVE = "INACTIVE"
    REAPPEARED = "REAPPEARED"
    EXCLUDED = "EXCLUDED"
    MERGED = "MERGED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class LaundryType(StrEnum):
    IN_UNIT_WASHER_DRYER_CONFIRMED = "IN_UNIT_WASHER_DRYER_CONFIRMED"
    IN_UNIT_WASHER_ONLY = "IN_UNIT_WASHER_ONLY"
    IN_UNIT_DRYER_ONLY = "IN_UNIT_DRYER_ONLY"
    IN_UNIT_HOOKUP_ONLY = "IN_UNIT_HOOKUP_ONLY"
    BUILDING_SHARED_LAUNDRY = "BUILDING_SHARED_LAUNDRY"
    OFFSITE_OR_NEARBY_LAUNDRY = "OFFSITE_OR_NEARBY_LAUNDRY"
    NO_LAUNDRY_STATED = "NO_LAUNDRY_STATED"
    EXPLICITLY_NO_LAUNDRY = "EXPLICITLY_NO_LAUNDRY"
    CONFLICTING = "CONFLICTING"
    UNKNOWN = "UNKNOWN"


class CanonicalResolutionStatus(StrEnum):
    RESOLVED = "RESOLVED"
    PROVISIONAL = "PROVISIONAL"
    CONFLICTING = "CONFLICTING"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class EnrichmentStatus(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    PENDING = "PENDING"
    PARTIAL = "PARTIAL"
    COMPLETE = "COMPLETE"
    STALE = "STALE"
    FAILED = "FAILED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class LinkStatus(StrEnum):
    ACTIVE = "ACTIVE"
    MISSING = "MISSING"
    REMOVED = "REMOVED"
    SUPERSEDED = "SUPERSEDED"
    CONFLICTING = "CONFLICTING"


class IdentityMethod(StrEnum):
    SOURCE_NATIVE_CONTINUITY = "SOURCE_NATIVE_CONTINUITY"
    EXACT_ADDRESS_AND_UNIT = "EXACT_ADDRESS_AND_UNIT"
    EXACT_BUILDING_UNIT_LAYOUT = "EXACT_BUILDING_UNIT_LAYOUT"
    STRONG_MULTI_FIELD = "STRONG_MULTI_FIELD"
    PROBABILISTIC_REVIEWED = "PROBABILISTIC_REVIEWED"
    MANUAL = "MANUAL"
    UNRESOLVED = "UNRESOLVED"


class IdentityConfidence(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    MANUAL = "MANUAL"


class MergeReasonCode(StrEnum):
    DUPLICATE_EXACT = "DUPLICATE_EXACT"
    DUPLICATE_PROBABILISTIC = "DUPLICATE_PROBABILISTIC"
    MANUAL = "MANUAL"


class PerformedByType(StrEnum):
    SYSTEM = "SYSTEM"
    LLM_PROPOSED_VALIDATED = "LLM_PROPOSED_VALIDATED"
    HUMAN = "HUMAN"


class DuplicateCandidateStatus(StrEnum):
    PENDING = "PENDING"
    AUTO_MERGED = "AUTO_MERGED"
    CONFIRMED_DUPLICATE = "CONFIRMED_DUPLICATE"
    CONFIRMED_DISTINCT = "CONFIRMED_DISTINCT"
    DEFERRED = "DEFERRED"


class FactEntityType(StrEnum):
    BUILDING = "BUILDING"
    UNIT = "UNIT"
    LISTING = "LISTING"
    MEDIA = "MEDIA"
    TRANSIT_ACCESS = "TRANSIT_ACCESS"
    COMMUTE_RESULT = "COMMUTE_RESULT"


class ValueStatus(StrEnum):
    ASSERTED = "ASSERTED"
    UNKNOWN = "UNKNOWN"
    NOT_STATED = "NOT_STATED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    NEGATIVE = "NEGATIVE"
    CONFLICTING = "CONFLICTING"


class DerivationType(StrEnum):
    SOURCE_STRUCTURED = "SOURCE_STRUCTURED"
    SOURCE_TEXT = "SOURCE_TEXT"
    LLM_DERIVED = "LLM_DERIVED"
    RULE_DERIVED = "RULE_DERIVED"
    PROVIDER_DERIVED = "PROVIDER_DERIVED"
    HUMAN = "HUMAN"


class ValidationStatus(StrEnum):
    PENDING = "PENDING"
    PASSED = "PASSED"
    WARNING = "WARNING"
    FAILED = "FAILED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class ResolutionStatus(StrEnum):
    RESOLVED = "RESOLVED"
    UNKNOWN = "UNKNOWN"
    CONFLICTING = "CONFLICTING"
    MANUAL_OVERRIDE = "MANUAL_OVERRIDE"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class ResolutionMethod(StrEnum):
    SOURCE_PRIORITY = "SOURCE_PRIORITY"
    RECENCY = "RECENCY"
    CONSENSUS = "CONSENSUS"
    RULE = "RULE"
    LLM_PROPOSED_VALIDATED = "LLM_PROPOSED_VALIDATED"
    HUMAN = "HUMAN"


class ModelTier(StrEnum):
    LOCAL = "LOCAL"
    DEFAULT_HOSTED = "DEFAULT_HOSTED"
    FLAGSHIP_ESCALATION = "FLAGSHIP_ESCALATION"


class ModelExecutionStatus(StrEnum):
    PENDING = "PENDING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CACHED = "CACHED"
    ESCALATED = "ESCALATED"


class AmenityScope(StrEnum):
    UNIT = "UNIT"
    BUILDING = "BUILDING"
    EITHER = "EITHER"


class AssertedScope(StrEnum):
    UNIT = "UNIT"
    BUILDING = "BUILDING"
    UNKNOWN = "UNKNOWN"


class PresenceStatus(StrEnum):
    PRESENT = "PRESENT"
    ABSENT = "ABSENT"
    UNKNOWN = "UNKNOWN"
    CONFLICTING = "CONFLICTING"


class MediaAvailabilityStatus(StrEnum):
    REFERENCED = "REFERENCED"
    STORED = "STORED"
    EXPIRED = "EXPIRED"
    REMOVED = "REMOVED"
    FAILED = "FAILED"
    POLICY_RESTRICTED = "POLICY_RESTRICTED"


class MediaType(StrEnum):
    UNIT_PHOTO = "UNIT_PHOTO"
    BUILDING_PHOTO = "BUILDING_PHOTO"
    AMENITY_PHOTO = "AMENITY_PHOTO"
    NEIGHBORHOOD_PHOTO = "NEIGHBORHOOD_PHOTO"
    FLOOR_PLAN = "FLOOR_PLAN"
    MAP = "MAP"
    LOGO = "LOGO"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class MediaClassificationStatus(StrEnum):
    UNCLASSIFIED = "UNCLASSIFIED"
    MODEL_CLASSIFIED = "MODEL_CLASSIFIED"
    RULE_CLASSIFIED = "RULE_CLASSIFIED"
    HUMAN_CONFIRMED = "HUMAN_CONFIRMED"
    CONFLICTING = "CONFLICTING"


class AssociationLevel(StrEnum):
    EXACT_UNIT_SOURCE_CONFIRMED = "EXACT_UNIT_SOURCE_CONFIRMED"
    SOURCE_UNIT_TYPE_CONFIRMED = "SOURCE_UNIT_TYPE_CONFIRMED"
    BUILDING_LAYOUT_CLASS = "BUILDING_LAYOUT_CLASS"
    BUILDING_GENERAL = "BUILDING_GENERAL"
    LISTING_SOURCE_ASSOCIATED = "LISTING_SOURCE_ASSOCIATED"
    UNCERTAIN_CANDIDATE = "UNCERTAIN_CANDIDATE"


class AssociationStatus(StrEnum):
    CONFIRMED = "CONFIRMED"
    PROVISIONAL = "PROVISIONAL"
    CANDIDATE = "CANDIDATE"
    REJECTED = "REJECTED"
    CONFLICTING = "CONFLICTING"


class TechnicalQualityStatus(StrEnum):
    PENDING = "PENDING"
    PASS = "PASS"
    WARNING = "WARNING"
    FAIL = "FAIL"


class ContentSafetyStatus(StrEnum):
    PENDING = "PENDING"
    PASS = "PASS"
    WARNING = "WARNING"
    BLOCKED = "BLOCKED"


class ContactOverlayStatus(StrEnum):
    NOT_DETECTED = "NOT_DETECTED"
    DETECTED = "DETECTED"
    REDACTED_COPY_AVAILABLE = "REDACTED_COPY_AVAILABLE"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    BLOCKED = "BLOCKED"


class WatermarkStatus(StrEnum):
    NONE_DETECTED = "NONE_DETECTED"
    PRESENT = "PRESENT"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    UNKNOWN = "UNKNOWN"


class MarketingUseStatus(StrEnum):
    PERMITTED = "PERMITTED"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"
    NOT_PERMITTED = "NOT_PERMITTED"
    UNKNOWN = "UNKNOWN"


class MediaVariantType(StrEnum):
    THUMBNAIL = "THUMBNAIL"
    PREVIEW = "PREVIEW"
    NORMALIZED = "NORMALIZED"
    PDF_PAGE_RENDER = "PDF_PAGE_RENDER"
    CONTACT_REDACTED_REVIEW_COPY = "CONTACT_REDACTED_REVIEW_COPY"


class MediaVariantUseScope(StrEnum):
    INTERNAL_REVIEW_ONLY = "INTERNAL_REVIEW_ONLY"
    MARKETING_CANDIDATE = "MARKETING_CANDIDATE"


class MediaAnalysisType(StrEnum):
    TYPE_CLASSIFICATION = "TYPE_CLASSIFICATION"
    ROOM_CLASSIFICATION = "ROOM_CLASSIFICATION"
    FLOORPLAN_ANALYSIS = "FLOORPLAN_ANALYSIS"
    TEXT_DETECTION = "TEXT_DETECTION"
    CONTACT_DETECTION = "CONTACT_DETECTION"
    QUALITY = "QUALITY"
    DUPLICATE_SIMILARITY = "DUPLICATE_SIMILARITY"


class MediaDuplicateType(StrEnum):
    EXACT = "EXACT"
    NEAR_DUPLICATE = "NEAR_DUPLICATE"
    DERIVATIVE = "DERIVATIVE"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class MediaDuplicateRelationship(StrEnum):
    EXACT = "EXACT"
    CROPPED = "CROPPED"
    RESIZED = "RESIZED"
    COMPRESSED = "COMPRESSED"
    WATERMARK_VARIANT = "WATERMARK_VARIANT"
    COLOR_VARIANT = "COLOR_VARIANT"
    OTHER = "OTHER"


class MediaDuplicateMemberStatus(StrEnum):
    AUTO_CONFIRMED = "AUTO_CONFIRMED"
    HUMAN_CONFIRMED = "HUMAN_CONFIRMED"
    CANDIDATE = "CANDIDATE"
    REJECTED = "REJECTED"


class TransitMode(StrEnum):
    SUBWAY = "SUBWAY"
    PATH = "PATH"
    BUS = "BUS"
    RAIL = "RAIL"
    FERRY = "FERRY"
    OTHER = "OTHER"


class TransitStopActiveStatus(StrEnum):
    ACTIVE = "ACTIVE"
    TEMPORARILY_CLOSED = "TEMPORARILY_CLOSED"
    INACTIVE = "INACTIVE"
    UNKNOWN = "UNKNOWN"


class UsefulnessStatus(StrEnum):
    USEFUL = "USEFUL"
    CANDIDATE = "CANDIDATE"
    NOT_USEFUL = "NOT_USEFUL"
    UNRESOLVED = "UNRESOLVED"


class TransitValidationStatus(StrEnum):
    PENDING = "PENDING"
    PASSED = "PASSED"
    WARNING = "WARNING"
    FAILED = "FAILED"
    UNABLE_TO_VALIDATE = "UNABLE_TO_VALIDATE"


class TransitServiceStatus(StrEnum):
    SCHEDULED = "SCHEDULED"
    ACTIVE = "ACTIVE"
    TEMPORARILY_CHANGED = "TEMPORARILY_CHANGED"
    UNKNOWN = "UNKNOWN"


class DestinationType(StrEnum):
    UNIVERSITY_CAMPUS = "UNIVERSITY_CAMPUS"
    MAJOR_DESTINATION = "MAJOR_DESTINATION"


class ProviderRequestType(StrEnum):
    GEOCODE = "GEOCODE"
    WALKING_ROUTE = "WALKING_ROUTE"
    TRANSIT_ROUTE = "TRANSIT_ROUTE"
    OTHER = "OTHER"


class ProviderRequestStatus(StrEnum):
    PENDING = "PENDING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CACHED = "CACHED"
    RATE_LIMITED = "RATE_LIMITED"


class TravelMode(StrEnum):
    PUBLIC_TRANSIT = "PUBLIC_TRANSIT"


class TimeBasis(StrEnum):
    DEPART_AT = "DEPART_AT"
    ARRIVE_BY = "ARRIVE_BY"
    CURRENT_OR_PROVIDER_DEFAULT = "CURRENT_OR_PROVIDER_DEFAULT"


class CommuteResultStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    NO_ROUTE = "NO_ROUTE"
    UNAVAILABLE = "UNAVAILABLE"
    PROVIDER_ERROR = "PROVIDER_ERROR"


class CommuteResultType(StrEnum):
    """B7 (2026-08-17): commutes may be provider routes or web-researched estimates."""

    PROVIDER_ROUTE = "PROVIDER_ROUTE"
    RESEARCHED_ESTIMATE = "RESEARCHED_ESTIMATE"


class DiscoveryMethod(StrEnum):
    """How a source link's listing was discovered (B3, 2026-08-17).

    SEARCH_INDEX links come from bounded site: search queries; their absence from
    search results is never disappearance evidence.
    """

    DIRECT = "DIRECT"
    SEARCH_INDEX = "SEARCH_INDEX"
    MANUAL_IMPORT = "MANUAL_IMPORT"
    UNKNOWN = "UNKNOWN"


class ListingEventType(StrEnum):
    CREATED = "CREATED"
    ACTIVATED = "ACTIVATED"
    MATERIAL_CHANGE = "MATERIAL_CHANGE"
    PRICE_CHANGED = "PRICE_CHANGED"
    AVAILABILITY_CHANGED = "AVAILABILITY_CHANGED"
    MEDIA_CHANGED = "MEDIA_CHANGED"
    LAUNDRY_CHANGED = "LAUNDRY_CHANGED"
    ADDRESS_CHANGED = "ADDRESS_CHANGED"
    MISSING_STARTED = "MISSING_STARTED"
    REAPPEARED = "REAPPEARED"
    INACTIVATED = "INACTIVATED"
    EXCLUDED = "EXCLUDED"
    MERGED = "MERGED"
    MANUAL_OVERRIDE_APPLIED = "MANUAL_OVERRIDE_APPLIED"
    MANUAL_OVERRIDE_REMOVED = "MANUAL_OVERRIDE_REMOVED"


class OverrideStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    REVOKED = "REVOKED"
    INVALIDATED = "INVALIDATED"


class OverrideReasonCode(StrEnum):
    SOURCE_ERROR = "SOURCE_ERROR"
    IDENTITY_CORRECTION = "IDENTITY_CORRECTION"
    CLASSIFICATION_CORRECTION = "CLASSIFICATION_CORRECTION"
    GEOGRAPHY_CORRECTION = "GEOGRAPHY_CORRECTION"
    MEDIA_CORRECTION = "MEDIA_CORRECTION"
    OTHER = "OTHER"


class ReviewIssueType(StrEnum):
    CONFLICT = "CONFLICT"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    DUPLICATE_CANDIDATE = "DUPLICATE_CANDIDATE"
    STALE = "STALE"
    VALIDATION_FAILURE = "VALIDATION_FAILURE"
    SOURCE_FAILURE = "SOURCE_FAILURE"
    MEDIA_ASSOCIATION = "MEDIA_ASSOCIATION"
    OTHER = "OTHER"


class ReviewIssueSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    BLOCKING = "BLOCKING"


class ReviewIssueStatus(StrEnum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"
    DISMISSED = "DISMISSED"


class SelectionStatus(StrEnum):
    SELECTED = "SELECTED"
    NOT_SELECTED = "NOT_SELECTED"
    REMOVED = "REMOVED"


class ShortlistEntryStatus(StrEnum):
    """Manual client-shortlist membership; fully independent of marketing selection.

    Live filter matches are computed at query time and are never persisted as
    entries (08 §16.3): only explicit human inclusion creates a row.
    """

    INCLUDED = "INCLUDED"
    EXCLUDED = "EXCLUDED"
    REMOVED = "REMOVED"


class JobType(StrEnum):
    NORMALIZE = "NORMALIZE"
    IDENTITY_RESOLVE = "IDENTITY_RESOLVE"
    RECONCILE = "RECONCILE"
    LLM_EXTRACT = "LLM_EXTRACT"
    MEDIA_FETCH = "MEDIA_FETCH"
    MEDIA_CLASSIFY = "MEDIA_CLASSIFY"
    FLOORPLAN_MATCH = "FLOORPLAN_MATCH"
    GEOCODE = "GEOCODE"
    TRANSIT_ENRICH = "TRANSIT_ENRICH"
    COMMUTE_ENRICH = "COMMUTE_ENRICH"
    VALIDATE = "VALIDATE"
    EXPORT = "EXPORT"


class JobStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_TERMINAL = "FAILED_TERMINAL"
    BLOCKED = "BLOCKED"
    CANCELLED = "CANCELLED"
    CACHED = "CACHED"


class ActorType(StrEnum):
    """Who performed a write. Used to enforce human-only actions in services."""

    HUMAN = "HUMAN"
    SYSTEM = "SYSTEM"
