# type: ignore
"""b3 b7 search discovery and researched commutes

Revision ID: 093c9fc3a73e
Revises: 9bb44a1b5855
Create Date: 2026-08-17 03:45:27.280110

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "093c9fc3a73e"
down_revision = "9bb44a1b5855"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "commute_result",
        sa.Column(
            "result_type",
            sa.Enum(
                "PROVIDER_ROUTE",
                "RESEARCHED_ESTIMATE",
                name="result_type_enum",
                native_enum=False,
                create_constraint=True,
                length=64,
            ),
            server_default="RESEARCHED_ESTIMATE",
            nullable=False,
        ),
        schema="app",
    )
    op.add_column(
        "commute_result", sa.Column("model_execution_id", sa.UUID(), nullable=True), schema="app"
    )
    op.add_column(
        "commute_result", sa.Column("duration_min_s", sa.Integer(), nullable=True), schema="app"
    )
    op.add_column(
        "commute_result", sa.Column("duration_max_s", sa.Integer(), nullable=True), schema="app"
    )
    op.add_column(
        "commute_result",
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        schema="app",
    )
    op.add_column(
        "commute_result",
        sa.Column(
            "confidence",
            sa.Enum(
                "HIGH",
                "MEDIUM",
                "LOW",
                "UNKNOWN",
                name="confidence_enum",
                native_enum=False,
                create_constraint=True,
                length=64,
            ),
            server_default="UNKNOWN",
            nullable=False,
        ),
        schema="app",
    )
    op.alter_column(
        "commute_result",
        "provider_request_id",
        existing_type=sa.UUID(),
        nullable=True,
        schema="app",
    )
    op.create_foreign_key(
        op.f("fk_commute_result_model_execution_id_model_execution"),
        "commute_result",
        "model_execution",
        ["model_execution_id"],
        ["model_execution_id"],
        source_schema="app",
        referent_schema="ops",
    )
    op.create_check_constraint(
        op.f("ck_commute_result_duration_range_ordered"),
        "commute_result",
        "duration_min_s IS NULL OR duration_max_s IS NULL OR duration_min_s <= duration_max_s",
        schema="app",
    )
    op.create_check_constraint(
        op.f("ck_commute_result_provider_route_requires_request"),
        "commute_result",
        "result_type <> 'PROVIDER_ROUTE' OR provider_request_id IS NOT NULL",
        schema="app",
    )
    op.create_check_constraint(
        op.f("ck_commute_result_research_requires_sources"),
        "commute_result",
        "result_type <> 'RESEARCHED_ESTIMATE' OR (model_execution_id IS NOT NULL AND sources IS NOT NULL AND jsonb_array_length(sources) > 0)",
        schema="app",
    )
    op.add_column(
        "listing_source_link",
        sa.Column(
            "discovery_method",
            sa.Enum(
                "DIRECT",
                "SEARCH_INDEX",
                "MANUAL_IMPORT",
                "UNKNOWN",
                name="discovery_method_enum",
                native_enum=False,
                create_constraint=True,
                length=64,
            ),
            server_default="UNKNOWN",
            nullable=False,
        ),
        schema="app",
    )
    # Manual: AVAILABLE may now be satisfied by a researched duration range.
    op.drop_constraint("available_requires_duration", "commute_result", schema="app", type_="check")
    op.create_check_constraint(
        "available_requires_duration",
        "commute_result",
        "result_status <> 'AVAILABLE' OR duration_s IS NOT NULL "
        "OR (duration_min_s IS NOT NULL AND duration_max_s IS NOT NULL)",
        schema="app",
    )
    # SourceType gained SEARCH_INDEX: replace the enum CHECK by hand (enum-value
    # changes are always hand-written migrations).
    op.drop_constraint("source_type_enum", "source", schema="app", type_="check")
    op.create_check_constraint(
        "source_type_enum",
        "source",
        "source_type IN ('LISTING', 'GEOCODER', 'ROUTING', 'TRANSIT_DATA', 'MEDIA', "
        "'SEARCH_INDEX', 'OTHER')",
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("source_type_enum", "source", schema="app", type_="check")
    op.create_check_constraint(
        "source_type_enum",
        "source",
        "source_type IN ('LISTING', 'GEOCODER', 'ROUTING', 'TRANSIT_DATA', 'MEDIA', 'OTHER')",
        schema="app",
    )
    op.drop_constraint("available_requires_duration", "commute_result", schema="app", type_="check")
    op.create_check_constraint(
        "available_requires_duration",
        "commute_result",
        "result_status <> 'AVAILABLE' OR duration_s IS NOT NULL",
        schema="app",
    )
    op.drop_column("listing_source_link", "discovery_method", schema="app")
    op.drop_constraint(
        op.f("ck_commute_result_research_requires_sources"),
        "commute_result",
        schema="app",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_commute_result_provider_route_requires_request"),
        "commute_result",
        schema="app",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_commute_result_duration_range_ordered"),
        "commute_result",
        schema="app",
        type_="check",
    )
    op.drop_constraint(
        op.f("fk_commute_result_model_execution_id_model_execution"),
        "commute_result",
        schema="app",
        type_="foreignkey",
    )
    op.alter_column(
        "commute_result",
        "provider_request_id",
        existing_type=sa.UUID(),
        nullable=False,
        schema="app",
    )
    op.drop_column("commute_result", "confidence", schema="app")
    op.drop_column("commute_result", "sources", schema="app")
    op.drop_column("commute_result", "duration_max_s", schema="app")
    op.drop_column("commute_result", "duration_min_s", schema="app")
    op.drop_column("commute_result", "model_execution_id", schema="app")
    op.drop_column("commute_result", "result_type", schema="app")
    # ### end Alembic commands ###
