# type: ignore
"""geographic boundary registry

Revision ID: 35bd168251db
Revises: 093c9fc3a73e
Create Date: 2026-08-17 17:33:30.757566

"""

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geography

revision = "35bd168251db"
down_revision = "093c9fc3a73e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "geographic_boundary",
        sa.Column(
            "geographic_boundary_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("region_code", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("region_group", sa.Text(), nullable=False),
        sa.Column(
            "geometry",
            Geography(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("dataset_version", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("geographic_boundary_id", name=op.f("pk_geographic_boundary")),
        sa.UniqueConstraint("region_code", name=op.f("uq_geographic_boundary_region_code")),
        schema="config",
    )
    op.create_geospatial_index(
        "idx_geographic_boundary_geometry",
        "geographic_boundary",
        ["geometry"],
        unique=False,
        schema="config",
        postgresql_using="gist",
        postgresql_ops={},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "idx_geographic_boundary_geometry",
        table_name="geographic_boundary",
        schema="config",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_table("geographic_boundary", schema="config")
    # ### end Alembic commands ###
