# type: ignore
"""company marketing selection

Revision ID: 45f4d0d1d668
Revises: 93d5b52a3b5e
Create Date: 2026-08-29 21:02:39.557788

"""
from alembic import op
import sqlalchemy as sa


revision = '45f4d0d1d668'
down_revision = '93d5b52a3b5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketing_selection', sa.Column('company_property_id', sa.UUID(), nullable=True), schema='app')
    op.alter_column('marketing_selection', 'canonical_listing_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='app')
    op.create_unique_constraint(op.f('uq_marketing_selection_company_property_id'), 'marketing_selection', ['company_property_id'], schema='app')
    op.create_foreign_key(op.f('fk_marketing_selection_company_property_id_company_property'), 'marketing_selection', 'company_property', ['company_property_id'], ['company_property_id'], source_schema='app', referent_schema='app', ondelete='CASCADE')
    op.create_check_constraint(op.f('ck_marketing_selection_exactly_one_target'), 'marketing_selection', 'num_nonnulls(canonical_listing_id, company_property_id) = 1', schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_marketing_selection_exactly_one_target'), 'marketing_selection', schema='app', type_='check')
    op.drop_constraint(op.f('fk_marketing_selection_company_property_id_company_property'), 'marketing_selection', schema='app', type_='foreignkey')
    op.drop_constraint(op.f('uq_marketing_selection_company_property_id'), 'marketing_selection', schema='app', type_='unique')
    op.alter_column('marketing_selection', 'canonical_listing_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='app')
    op.drop_column('marketing_selection', 'company_property_id', schema='app')
    # ### end Alembic commands ###
