# type: ignore
"""company property registry

Revision ID: 4e11e1c637fe
Revises: 35bd168251db
Create Date: 2026-08-29 18:08:36.836324

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '4e11e1c637fe'
down_revision = '35bd168251db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_property',
    sa.Column('company_property_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_fingerprint', sa.Text(), nullable=False),
    sa.Column('source_document', sa.Text(), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=True),
    sa.Column('resolved_url', sa.Text(), nullable=True),
    sa.Column('resolved_url_kind', sa.Text(), nullable=True),
    sa.Column('link_status', sa.Text(), server_default='UNCHECKED', nullable=False),
    sa.Column('address_text', sa.Text(), nullable=True),
    sa.Column('locality', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('matched_building_id', sa.UUID(), nullable=True),
    sa.Column('availability', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('check_status', sa.Text(), server_default='PENDING', nullable=False),
    sa.Column('check_error', sa.Text(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matched_building_id'], ['app.building.building_id'], name=op.f('fk_company_property_matched_building_id_building'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('company_property_id', name=op.f('pk_company_property')),
    sa.UniqueConstraint('name_fingerprint', name=op.f('uq_company_property_name_fingerprint')),
    schema='app'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_property', schema='app')
    # ### end Alembic commands ###
