# type: ignore
"""company shortlist entries

Revision ID: 93d5b52a3b5e
Revises: 4e11e1c637fe
Create Date: 2026-08-29 19:48:47.072265

"""
from alembic import op
import sqlalchemy as sa


revision = '93d5b52a3b5e'
down_revision = '4e11e1c637fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_shortlist_entry', sa.Column('company_property_id', sa.UUID(), nullable=True), schema='app')
    op.alter_column('client_shortlist_entry', 'canonical_listing_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='app')
    op.create_unique_constraint(op.f('uq_client_shortlist_entry_client_search_preset_id_company_property_id'), 'client_shortlist_entry', ['client_search_preset_id', 'company_property_id'], schema='app')
    op.create_foreign_key(op.f('fk_client_shortlist_entry_company_property_id_company_property'), 'client_shortlist_entry', 'company_property', ['company_property_id'], ['company_property_id'], source_schema='app', referent_schema='app', ondelete='CASCADE')
    op.create_check_constraint(op.f('ck_client_shortlist_entry_exactly_one_target'), 'client_shortlist_entry', 'num_nonnulls(canonical_listing_id, company_property_id) = 1', schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_client_shortlist_entry_exactly_one_target'), 'client_shortlist_entry', schema='app', type_='check')
    op.drop_constraint(op.f('fk_client_shortlist_entry_company_property_id_company_property'), 'client_shortlist_entry', schema='app', type_='foreignkey')
    op.drop_constraint(op.f('uq_client_shortlist_entry_client_search_preset_id_company_property_id'), 'client_shortlist_entry', schema='app', type_='unique')
    op.alter_column('client_shortlist_entry', 'canonical_listing_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='app')
    op.drop_column('client_shortlist_entry', 'company_property_id', schema='app')
    # ### end Alembic commands ###
