# type: ignore
"""company check log

Revision ID: a25dc39feba2
Revises: 39a0f7866dca
Create Date: 2026-08-29 22:36:18.451253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'a25dc39feba2'
down_revision = '39a0f7866dca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_property', sa.Column('check_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_property', 'check_log', schema='app')
    # ### end Alembic commands ###
